### PR TITLE
add docker build files for creating an image for concourse

### PR DESCRIPTION
**Pull request by randomtask1155**

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
Would you have any objections to putting these two new files into a subfolder under `vSphere/`? Like `concourse` or `ci`? Just thinking how we could stash them away so they are not confusing if someone manually runs this repo.

Also, maybe mention them in the README? Like 'These are only used by Concourse, you only need to use them if x, y, z occurs.'?

**Comment by randomtask1155** [comment]
i can mention them in the readme but the DockerFile sorta has to be there in root in order for it to properly create the docker image based off of the cloud cleaner stuff.

**Comment by dmikusa-pivotal** [comment]
OK, not a big deal. Let's just add something to the README so it doesn't confuse people.

**Comment by dmikusa-pivotal** [comment]
I added a note here -> https://github.com/pivotal-gss/pcf-cloud-cleaner/blob/master/vSphere/README.md#concourse-usage

Could you follow up and add an example of how someone might use that script/docker image?

**Comment by randomtask1155** [comment]
closing the loop.. i updated the readme

**Pull request merged**
